#!/usr/bin/env bash
#
# Idempotent installer for you-terminal-player.
# Sets up everything so that afterwards you can just run `yt` in any terminal:
#   - ffmpeg / ffplay (video + audio)
#   - a Node.js runtime (for yt-dlp's "n" signature / JS challenge)
#   - the Python venv + yt-dlp[default] (EJS) + bgutil PO-token plugin
#   - the bgutil PO-token server (Docker, port 4416)
#   - a global `yt` launcher on your PATH
#
# Safe to re-run. Usage:  ./install.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
VENV="$PROJECT_DIR/.venv"
CONTAINER="bgutil-provider"
POT_PORT=4416

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
log()  { printf '  \033[32m✓\033[0m %s\n' "$*"; }
info() { printf '  \033[36m→\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

bold "you-terminal-player — Setup"
echo

# --- 1. macOS + Homebrew --------------------------------------------------
[ "$(uname)" = "Darwin" ] || warn "Not macOS — proceeding, but only tested on macOS."
if ! command -v brew >/dev/null 2>&1; then
    die "Homebrew not found. Install it from https://brew.sh and re-run this script."
fi
log "Homebrew found"

# --- 2. ffmpeg / ffplay ---------------------------------------------------
if command -v ffmpeg >/dev/null 2>&1 && command -v ffplay >/dev/null 2>&1; then
    log "ffmpeg & ffplay present"
else
    info "Installing ffmpeg (provides ffmpeg + ffplay)…"
    brew install ffmpeg
    log "ffmpeg installed"
fi

# --- 3. Node.js (>= 22) for yt-dlp's JS challenge solver -------------------
node_major() { node --version 2>/dev/null | sed 's/^v//' | cut -d. -f1; }
if command -v node >/dev/null 2>&1 && [ "$(node_major)" -ge 22 ] 2>/dev/null; then
    log "Node.js $(node --version) present"
else
    info "Installing Node.js (>= 22 required)…"
    brew install node
    log "Node.js installed"
fi
NODE_DIR="$(dirname "$(command -v node)")"
info "Node directory: $NODE_DIR"

# --- 4. Python venv + packages --------------------------------------------
SIBLING="$(cd "$PROJECT_DIR/.." && pwd)/first-grok-build"
[ -d "$SIBLING" ] || die "Required sibling project not found: $SIBLING"

if [ ! -x "$VENV/bin/python" ]; then
    info "Creating virtualenv…"
    python3 -m venv "$VENV"
fi
log "virtualenv ready"

info "Installing Python packages (this can take a minute)…"
"$VENV/bin/python" -m pip install -q --upgrade pip
"$VENV/bin/python" -m pip install -q -e "$PROJECT_DIR[dev]"
"$VENV/bin/python" -m pip install -q -U --pre "yt-dlp[default]" bgutil-ytdlp-pot-provider
log "yt-dlp[default] + EJS + bgutil plugin installed"

# --- 5. Docker + bgutil PO-token server -----------------------------------
DOCKER_OK=0
if ! command -v docker >/dev/null 2>&1; then
    warn "Docker not found — YouTube needs the PO-token server."
    warn "Install Docker Desktop:  brew install --cask docker   (then re-run this script)"
else
    if ! docker info >/dev/null 2>&1; then
        info "Starting Docker Desktop…"
        open -a Docker 2>/dev/null || true
        for _ in $(seq 1 60); do
            docker info >/dev/null 2>&1 && break
            sleep 1
        done
    fi
    if docker info >/dev/null 2>&1; then
        DOCKER_OK=1
        if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER"; then
            docker start "$CONTAINER" >/dev/null
            log "PO-token server (existing container) started"
        else
            info "Launching bgutil PO-token server…"
            docker run -d --init --restart unless-stopped \
                -p "$POT_PORT:$POT_PORT" --name "$CONTAINER" \
                brainicism/bgutil-ytdlp-pot-provider >/dev/null
            log "PO-token server launched"
        fi
        # Wait until the server answers.
        for _ in $(seq 1 20); do
            curl -sf -m 2 "http://127.0.0.1:$POT_PORT/ping" >/dev/null 2>&1 && break
            sleep 0.5
        done
        curl -sf -m 2 "http://127.0.0.1:$POT_PORT/ping" >/dev/null 2>&1 \
            && log "PO-token server responding on :$POT_PORT" \
            || warn "PO-token server not responding yet on :$POT_PORT"
    else
        warn "Docker daemon not running — start Docker Desktop, then re-run this script."
    fi
fi

# --- 6. Global `yt` launcher on PATH --------------------------------------
# Prefer Homebrew's bin (on PATH, writable, no sudo); fall back to ~/.local/bin.
if [ -w "$(brew --prefix)/bin" ]; then
    BIN_DIR="$(brew --prefix)/bin"
else
    BIN_DIR="$HOME/.local/bin"
    mkdir -p "$BIN_DIR"
fi
LAUNCHER="$BIN_DIR/yt"

cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Auto-generated by you-terminal-player/install.sh
export PATH="$NODE_DIR:\$PATH"                          # ensure Node for nsig solving
docker start $CONTAINER >/dev/null 2>&1 || true          # ensure PO-token server is up
exec "$VENV/bin/yt" "\$@"
EOF
chmod +x "$LAUNCHER"
log "Installed launcher: $LAUNCHER"
case ":$PATH:" in
    *":$BIN_DIR:"*) : ;;
    *) warn "$BIN_DIR is not on your PATH — add it to ~/.zshrc:  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

# --- 7. Smoke test + usage ------------------------------------------------
"$VENV/bin/yt" --help >/dev/null 2>&1 && log "yt command works"
echo
bold "Done! 🎉  Terminal-TV is ready."
echo
echo "  yt                         # play the default video"
echo "  yt \"<youtube-url>\"          # play a specific video"
echo "  yt --cookies-from-browser safari \"<url>\"   # if YouTube asks 'not a bot'"
echo
echo "  Controls:  [space] pause/resume   [q] quit"
[ "$DOCKER_OK" = "1" ] || echo "  NOTE: start Docker Desktop and re-run this script for YouTube playback."
echo "  Tip: a bigger window + smaller font (Cmd -) = sharper picture."
