#!/usr/bin/env bash
#
# Uninstaller for you-terminal-player. Reverses install.sh:
#   - removes the global `yt` launcher (only if it's ours)
#   - stops & removes the bgutil PO-token Docker container
#   - removes the .venv
#
# It deliberately keeps shared tools (ffmpeg, Node, Docker) and the project
# source. Safe to re-run. Usage:  ./uninstall.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
VENV="$PROJECT_DIR/.venv"
CONTAINER="bgutil-provider"
MARKER="Auto-generated by you-terminal-player/install.sh"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
log()  { printf '  \033[32m✓\033[0m %s\n' "$*"; }
info() { printf '  \033[36m→\033[0m %s\n' "$*"; }

bold "you-terminal-player — Uninstall"
echo

# --- 1. Global `yt` launcher (only remove our own) ------------------------
removed_launcher=0
for dir in "$(brew --prefix 2>/dev/null)/bin" "$HOME/.local/bin"; do
    f="$dir/yt"
    if [ -f "$f" ] && grep -q "$MARKER" "$f" 2>/dev/null; then
        rm -f "$f"
        log "Removed launcher: $f"
        removed_launcher=1
    fi
done
[ "$removed_launcher" = "1" ] || info "No you-terminal-player launcher found (skipped)."

# --- 2. bgutil PO-token Docker container ----------------------------------
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER"; then
        docker rm -f "$CONTAINER" >/dev/null
        log "Removed Docker container: $CONTAINER"
    else
        info "No '$CONTAINER' container (skipped)."
    fi
    # The image is left in place; remove it manually if you want:
    info "To also drop the image:  docker rmi brainicism/bgutil-ytdlp-pot-provider"
else
    info "Docker not running — remove the '$CONTAINER' container manually if needed."
fi

# --- 3. Virtualenv --------------------------------------------------------
if [ -d "$VENV" ]; then
    rm -rf "$VENV"
    log "Removed virtualenv: $VENV"
else
    info "No .venv found (skipped)."
fi

echo
bold "Uninstalled. 👋"
echo "  Kept: project source, and shared tools (ffmpeg, Node, Docker)."
echo "  Remove the whole project with:  rm -rf \"$PROJECT_DIR\""
